language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
script: tox -e $TOX_ENV
install:
    - pip install tox
matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.6
      env:
        - TOX_ENV=flake8
